### ISSUE TITLE
Census does not include current hospitalizations

### ISSUE THREAD

**Issue by asalil** [CodeForPhilly/chime#203] opened 2020-03-23 18:17 UTC
Why does the day 0 not include current hospitalizations? For example, if I put in 4 currently hospitalized COVID-19 patients at the top of parameters, that doesn't show up in the Census numbers.

**Comment by PhilMiller** [comment] 2020-03-23 20:10
This is a duplicate of #187. My fix was just posted for review.

**Closed as completed** 2020-03-24 00:27 UTC
