### ISSUE TITLE
["model"]

### ISSUE THREAD

**Issue by jlubken** [CodeForPhilly/chime#449] opened 2020-04-02 18:45 UTC
### Summary

Prefit policies are not assembled correctly for distancing < day 0.

### Additional details

current_date census does not line up with the with the user's entered currently_hospitalized after fitting.

### Suggested fix

Check how the policies are assembled for the prefit curve.

**Comment by PhilMiller** [comment] 2020-04-02 19:51
@cjbayesian Could you post any details of what you're seeing? I'll follow up on this as needed, but don't want to repeat work or miss the point.

**Comment by PhilMiller** [comment] 2020-04-02 21:19
Ok, I can see this now, after playing with things for a bit. It doesn't require distancing to be applied at all. The problem is that with just the doubling time parameter to work with, the possible values of the simulated census are discretized by the increments of the doubling time.

I've tried running the doubling time fit at higher resolution naively, and it does indeed get a lot slower. I'll write some iterative refinement code for that instead which should be much better.

**Comment by PhilMiller** [comment] 2020-04-02 21:45
Have a look at branch `refined-fitting`

**Comment by PhilMiller** [comment] 2020-04-02 21:50
It's a lot closer, but without burning a bunch more cycles, or spending more time optimizing the code's performance, it's not going to be exact

**Comment by PhilMiller** [comment] 2020-04-02 22:01
#456 gets an annoyance out of the way, and would ideally be merged in short order.

**Closed as completed** 2020-04-02 22:33 UTC
Labels: models
