### ISSUE TITLE
[bug] Incorrect doubling time for social distancing values above 63%

### ISSUE THREAD

**Issue by ecsmyth** [CodeForPhilly/chime#155] opened 2020-03-20 21:33 UTC
### STR
1. Load CHIME (https://penn-chime.phl.io/)
2. Set `Social distancing (% reduction in social contact)` to a value below 64 while leaving other values at the default.
2. Repeat step 2 with a value above 63

### Observed
Doubling times are negative when the social distancing value is greater than 63%

Social Distancing (%) | Doubling Time (days) | Rt
-- | -- | --
0 | 6 | 2.71
25 | 9.7 | 2.04
50 | 27.5 | 1.36
60 | 113.5 | 1.09
63 | 2229.4 | 1
64 | -425.4 | 0.98

### Expected
Doubling times are always positive. When `Rt < 1`, unit of time should still be positive and the summary text should indicate that infections will halve over the period of time, not double.

**Comment by quinn-dougherty** [comment] 2020-03-21 14:17
![Screenshot from 2020-03-21 10-17-17](https://user-images.githubusercontent.com/39039420/77228366-2bd91900-6b5d-11ea-96b5-101580049c02.png)

**Comment by mdbecker** [comment] 2020-03-22 19:27
As stated, this is not a bug. Closing.

**Comment by cjbayesian** [comment] 2020-03-23 19:20
Spoke with @ecsmyth and clarified his intention with this issue:
>My issue wasn't with the implication of Rt < 1, but rather than the summation using a negative unit of time. I was thinking of a change like:
```
Mitigation: A 0% reduction in social contact after the onset of the outbreak reduces the doubling time to 6.0 days, implying an effective Rt​ of 2.71.
Mitigation: A 65% reduction in social contact after the onset of the outbreak halves the infections every 194.0 days, implying an effective Rt of 0.95.
```

**Closed as completed** 2020-03-24 19:55 UTC
Labels: bug
