### ISSUE TITLE
document devops structure

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/chime#81] opened 2020-03-19 02:03 UTC
What has the ops team built?  How does it help the app? 

Make documentation for app stakeholders to show what/why we built what we built

**Comment by garysieling** [comment] 2020-03-19 13:39
Initial notes (maybe someone can add color to the first item)
- Kubernetes stuff (scaling, logging to elasticsearch)
- Implemented a standard API for scripts for executing the app ("rule them all")
- Parallel ability to deploy to Kubernetes + Heroku so users can pick what they want
- CI - gating of commits for quality checks, construction of docker container of the app

**Comment by themightychris** [comment] 2020-03-19 17:39
How do we actually want to change the docs though to close this issue? https://codeforphilly.github.io/chime/

Most of this is already touched on. Do we just need to fill some gaps in? Add a new overview page?

**Comment by mariekers** [comment] 2020-04-17 19:59
@lottspot if we're planning on moving away from development on the app, is this still useful?  Would it be helpful in outlining how cfp hosts projects in the future?

**Comment by rcknplyr** [comment] 2020-04-21 03:19
Closing this issue in this repo. Content/intent of the issue is valid - let's address in Chime2.0 repo.

**Closed by rcknplyr** 2020-04-21 03:19 UTC
Labels: documentation, future
